Vagrant.configure("2") do |config|

  #
  # Environment Variables
  #
  SCRIPT_FOLDER  = "../scripts"
  IMAGE_NAME     = "aruns1975/spark-3.2.1"
  IMAGE_VERSION  = "1.0"

  MACHINE_NAME   = "spark-worker-node"
  MACHINE_IP    = "10.1.0.1"

  #
  # Creations of user and installation of java, scala and git
  #
  #config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/create_user.sh"
  #config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_base_softwares.sh"
  #config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_spark.sh"

 
  #
  # Master node configuration
  #
  config.vm.define "#{MACHINE_NAME}" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.box_version = IMAGE_VERSION
    master.vm.hostname = "#{MACHINE_NAME}"
    master.vm.network "private_network", ip: MACHINE_IP
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    master.name="#{MACHINE_NAME}"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/start_spark_server.sh"
    end
  end
end