Vagrant.configure("2") do |config|

    #
    # Environment Variables
    #
    SCRIPT_FOLDER  = "../../scripts"
    IMAGE_NAME     = "aruns1975/minio-s3-server"
    IMAGE_VERSION  = "2.0"
  
    MACHINE_NAME   = "s3-server"
    MACHINE_IP    = "10.1.1.100"
  
    config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/create_user_minio.sh"
    config.vm.provision "shell", inline: <<-SHELL
        echo "127.0.0.1       localhost" > /etc/hosts
        echo " " >> /etc/hosts
        echo "# The following lines are desirable for IPv6 capable hosts"  >> /etc/hosts
        echo "::1     ip6-localhost   ip6-loopback" >> /etc/hosts
        echo "fe00::0 ip6-localnet" >> /etc/hosts
        echo "ff00::0 ip6-mcastprefix" >> /etc/hosts
        echo "ff02::1 ip6-allnodes" >> /etc/hosts
        echo "ff02::2 ip6-allrouters" >> /etc/hosts
        echo "ff02::3 ip6-allhosts" >> /etc/hosts
        #echo "127.0.1.1  spark-master-node spark-master-node" >> /etc/hosts
        echo " " >> /etc/hosts
        echo "10.1.1.100  s3-server" >> /etc/hosts
    SHELL
    #
  # Master node configuration
  #
  config.vm.define "#{MACHINE_NAME}" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.box_version = IMAGE_VERSION
    master.vm.hostname = "#{MACHINE_NAME}"
    master.vm.network "private_network", ip: MACHINE_IP
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    vb.name="#{MACHINE_NAME}"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/start_minio.sh"
    end
  end
end
  