Vagrant.configure("2") do |config|

  #
  # Environment Variables
  #
  SCRIPT_FOLDER  = "../../scripts"
  IMAGE_NAME     = "ubuntu/focal64"
  IMAGE_VERSION  = "20210624.0.0"

  MACHINE_NAME   = "spark-master-node"
  MACHINE_IP    = "10.1.1.100"

  #
  # Creations of user and installation of java, scala and git
  #
  config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/create_user.sh"
  #config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_base_softwares.sh"
  #config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_spark.sh"

 
  #
  # Master node configuration
  #
  config.vm.define "#{MACHINE_NAME}" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.box_version = IMAGE_VERSION
    master.vm.hostname = "#{MACHINE_NAME}"
    master.vm.network "private_network", ip: MACHINE_IP
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    vb.name="#{MACHINE_NAME}"
    end
  end
end